CREATE UNIQUE INDEX [IX_Username_Password] ON [Users]([Username], [Password]);
CREATE UNIQUE INDEX [IX_SysName] ON [RetailSystems]([SysName]);
CREATE INDEX [IX_ReqDetailNo] ON [Reqs]([ReqDetailNo]);
CREATE INDEX [IX_AcptDate] ON [Reqs]([AcptDate] DESC);
CREATE INDEX [IX_BusiReqNo] ON [BusiReqs]([BusiReqNo]);
CREATE UNIQUE INDEX [IX_ProjName] ON [Projs]([ProjName]);
CREATE INDEX [IX_SysId_VerYear] ON [Vers]([SysId], [VerYear]);
CREATE INDEX [IX_RptDate] ON [WeekReportDetails]([RptDate]);
CREATE INDEX [IX_RptDate] ON [WeekReportRisks]([RptDate]);

insert into Users (Username, Password, Realname, Phone, IsAdmin) values ('admin', 'E10ADC3949BA59ABBE56E057F20F883E', N'管理员', '801157', 1);
insert into Users (Username, Password, Realname, Phone, IsAdmin) values ('011189', '96E79218965EB72C92A549DD5A330112', N'宋晨崴', '801110', 1);
insert into Users (Username, Password, Realname, Phone, IsAdmin) values ('011378', '96E79218965EB72C92A549DD5A330112', N'赵欣', '801111', 0);
insert into Users (Username, Password, Realname, Phone, IsAdmin) values ('011482', '96E79218965EB72C92A549DD5A330112', N'杨洋', '801112', 0);
insert into Users (Username, Password, Realname, Phone, IsAdmin) values ('014561', '96E79218965EB72C92A549DD5A330112', N'史伟', '801113', 0);
insert into Users (Username, Password, Realname, Phone, IsAdmin) values ('014691', '96E79218965EB72C92A549DD5A330112', N'陈瑞华', '801156', 0);
insert into Users (Username, Password, Realname, Phone, IsAdmin) values ('014690', '96E79218965EB72C92A549DD5A330112', N'周梦', '801157', 0);
insert into Users (Username, Password, Realname, Phone, IsAdmin) values ('011484', '96E79218965EB72C92A549DD5A330112', N'柴军', '801157', 0);
insert into Users (Username, Password, Realname, Phone, IsAdmin) values ('019106', '96E79218965EB72C92A549DD5A330112', N'陶昱东', '808849', 0);
insert into Users (Username, Password, Realname, Phone, IsAdmin) values ('019107', '96E79218965EB72C92A549DD5A330112', N'金之阜', '808849', 0);
insert into Users (Username, Password, Realname, Phone, IsAdmin) values ('019118', '96E79218965EB72C92A549DD5A330112', N'张娟', '808849', 0);

insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('C035X0', N'保险代销系统', N'银保通', N'零售银行管理总部', N'财富和负债管理部', N'曾鸣', N'上海研发', N'包强', 3);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('C028X0', N'储蓄电子国债销售系统', N'储蓄电子国债', N'零售银行管理总部', N'财富和负债管理部', N'严思琼', N'福州研发', N'翁乐炜', 3);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('K012Q0', N'客户关系管理系统(OCRM)', N'客户关系管理系统', N'零售银行管理总部', N'客户发展部', N'唐锦', N'上海研发', N'孙国栋', 7);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('K013X0', N'客户关系管理系统(ACRM)', N'客户关系管理系统', N'零售银行管理总部', N'客户发展部', N'唐锦', N'上海研发', N'孙国栋', 7);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('J021L0', N'零售数据集市', N'零售数据集市', N'零售银行管理总部', N'业务管理部', N'刘学军', N'上海研发', N'孙国栋', 7);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('C021X0', N'零售信贷系统', N'零售信贷', N'零售银行管理总部', N'信贷管理部', N'史天艺', N'上海研发', N'杨占奇', 5);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('F004X0', N'人行个人征信接口系统', N'个人征信接口', N'零售银行管理总部', N'信贷管理部', N'王为宁', N'上海研发', N'杨樟柏', 5);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('G008X0', N'零售信贷报表系统', N'零售信贷报表', N'零售银行管理总部', N'信贷管理部', N'史天艺', N'上海研发', N'彭益峰', 5);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('F013X0', N'零售信贷风险分类系统', N'零售信贷分析系统', N'零售银行管理总部', N'信贷管理部', N'史天艺', N'上海研发', N'彭益峰', 5);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('C021X1', N'零售信贷影像档案管理系统', N'零售信贷影像档案管理系统', N'零售银行管理总部', N'信贷管理部', N'史天艺', N'上海研发', N'杨占奇', 5);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('W004X0', N'公民身份信息核查系统', N'身份证核查', N'零售银行管理总部', N'银行卡及渠道管理部', N'张庆', N'福州研发', N'陈韦韦', 4);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('C007X0', N'福建省移动代缴系统（中间业务平台2.0）', N'闽移动代缴', N'零售银行管理总部', N'银行卡及渠道管理部', N'陈仕烨', N'福州研发', N'翁乐炜', 4);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('W002L0', N'全国金卡系统', N'全国金卡', N'零售银行管理总部', N'银行卡及渠道管理部', N'蒋勤洁', N'福州研发', N'赵艺林', 6);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('W003X0', N'福建省金卡系统', N'闽金卡', N'零售银行管理总部', N'银行卡及渠道管理部', N'蒋勤洁', N'福州研发', N'赵艺林', 6);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('W006X0', N'福建省内分行兴业通系统', N'闽兴业通', N'零售银行管理总部', N'银行卡及渠道管理部', N'陈仕烨', N'福州研发', N'赵艺林', 6);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('Z004X0', N'理财卡外包制卡系统', N'外包制卡', N'零售银行管理总部', N'银行卡及渠道管理部', N'陈仕烨', N'福州研发', N'陈怀杰', 4);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('Z014X0', N'零售柜面模拟培训系统', N'柜面培训系统', N'零售银行管理总部', N'银行卡及渠道管理部', N'刘娟', N'福州研发', N'陈韦韦', 4);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('G006X0', N'零售绩效考核系统', N'零售绩效考核', N'零售银行管理总部', N'零售业务管理部', N'储飞', N'上海研发', N'姜国华', 3);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values (N'暂无', N'零售信息共享平台', N'零售信息共享平台', N'零售银行管理总部', N'零售业务管理部', N'周夕入', N'上海研发', N'李春霞', 3);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('C002X0', N'银联数据综合前置系统（中间业务平台3.0）', N'信用卡前置/银联数据前置', N'信用卡中心', N'信用卡中心', N'蒋辉', N'福州研发', N'翁乐炜', 6);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('Q010X0', N'信用卡商城系统', N'信用卡商城', N'信用卡中心', N'信用卡中心', N'叶茂', N'上海研发', N'何平', 4);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('K004Q0', N'企业级客户信息交换系统', N'客户信息交换系统', N'信息科技部', N'信息科技部', N'', N'上海研发', N'张俊霞', 4);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('C033X0', N'IC借记卡系统', N'金融IC借记卡', N'零售银行管理总部', N'银行卡及渠道管理部', N'陈仕烨', N'上海研发', N'江庆', 6);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values (N'暂无', N'分行金卡系统基准版', N'', N'零售银行管理总部', N'银行卡及渠道管理部', N'蒋勤洁', N'福州研发', N'赵艺林', 6);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('G006X0', N'零售业务人员信息服务系统', N'零售业务人员信息服务系统', N'零售银行管理总部', N'零售业务管理部', N'顾于斌', N'上海研发', N'姜国华', 7);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('C042X0', N'统一代扣代缴平台', N'统一代扣代缴平台', N'零售银行管理总部', N'银行卡及渠道管理部', N'朱海歌', N'福州研发', N'谢茂善', 4);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('C036X0', N'实物产品销售管理系统', N'实物产品销售管理系统', N'零售银行管理总部', N'财富和负债管理部', N'米为振', N'上海研发', N'张锐', 3);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('C019X0', N'零售代理类产品销售管理系统', N'零售代理类产品销售', N'零售银行管理总部', N'财富和负债管理部', N'曾鸣', N'上海研发', N'孙建军', 7);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('G008X0', N'零售条线统一数据分析及报表平台', N'零售条线报表系统', N'零售银行管理总部', N'业务管理部', N'刘学军', N'上海研发', N'孙国栋', 5);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('K015Q0', N'零售客户信息管理系统', N'零售CIF', N'零售银行管理总部', N'财富和负债管理部', N'吴益军', N'福州研发', N'严圣', 7);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('K012X1', N'财富规划及资产配置信息系统', N'零售财富规划系统', N'零售银行管理总部', N'财富和负债管理部', N'陈晓', N'上海研发', N'江雪晶', 3);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values ('C046X0', N'个人结售汇系统与电子渠道外汇汇款系统', N'个人结售汇系统', N'零售银行管理总部', N'银行卡及渠道管理部', N'刘婷', N'福州研发', N'郑占平', 6);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values (N'暂无', N'私人银行业务管理项目', N'私行系统', N'', N'私人银行部', N'高翔', N'上海研发', N'江雪晶', 5);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values (N'暂无', N'安愉人生养老金融项目', N'安愉人生养老金融', N'', N'财富和负债管理部', N'严思琼', N'上海研发', N'杭佳文', 6);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values (N'暂无', N'储蓄电子国债二期项目', N'储蓄电子国债升级', N'', N'财富和负债管理部', N'严思琼', N'福州研发', N'翁乐炜', 4);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values (N'暂无', N'零售业务人员信息服务系统二期项目', N'RPHM二期', N'', N'业务管理部', N'刘学军', N'上海研发', N'姜国华', 7);
insert into RetailSystems (SysNO, SysName, SysShortName, HostDept, SecondDept, BusiPerson, DevCenter, DevPerson, ReqPersonID) values (N'暂无', N'金融产品互市交易平台项目', N'金融互市交易平台', N'', N'财富和负债管理部', N'苏健', N'', N'', 6);